import { User } from '@types';

export const userList: User[] = [
  { id: '1', name: '박상훈', tier: 2, gender: 'M' },
  { id: '0', name: '이영철', tier: 2, gender: 'M' },
  { id: '2', name: '김동현', tier: 2, gender: 'M' },
  { id: '3', name: '김승준', tier: 4, gender: 'M' },
  { id: '4', name: '이찬진', tier: 2, gender: 'M' },
  { id: '5', name: '주성표', tier: 2, gender: 'M' },
  { id: '6', name: '강민경', tier: 5, gender: 'F' },
  { id: '7', name: '강준혁', tier: 99, gender: 'M' },
  { id: '8', name: '김다은', tier: 5, gender: 'F' },
  { id: '9', name: '이지영', tier: 4, gender: 'F' },
  { id: '10', name: '임인영', tier: 3, gender: 'M' },
  { id: '11', name: '전현민', tier: 1, gender: 'M' },
  { id: '12', name: '정승민', tier: 4, gender: 'M' },
  { id: '13', name: '조예린', tier: 5, gender: 'F' },
  { id: '14', name: '은지', tier: 99, gender: 'F' },
  { id: '15', name: '이명재', tier: 4, gender: 'M' },
  { id: '16', name: '이세광', tier: 4, gender: 'M' },
  { id: '17', name: '이용표', tier: 99, gender: 'M' },
  { id: '18', name: '이정우', tier: 99, gender: 'M' },
  { id: '19', name: '안광휘', tier: 3, gender: 'M' },
  { id: '20', name: '안효원', tier: 1, gender: 'M' },
  { id: '21', name: '영연', tier: 5, gender: 'M' },
  { id: '22', name: '용준', tier: 5, gender: 'M' },
  { id: '23', name: '은중', tier: 99, gender: 'M' },
  { id: '24', name: '배성우', tier: 99, gender: 'M' },
  { id: '25', name: '서주승', tier: 99, gender: 'M' },
  { id: '26', name: '승연', tier: 2, gender: 'M' },
  { id: '27', name: '신다은', tier: 5, gender: 'F' },
  { id: '28', name: '신동건', tier: 1, gender: 'M' },
  { id: '29', name: '김지영', tier: 99, gender: 'F' },
  { id: '30', name: '김찬엽', tier: 2, gender: 'M' },
  { id: '31', name: '다희', tier: 5, gender: 'F' },
  { id: '32', name: '민제', tier: 2, gender: 'M' },
  { id: '33', name: '박지훈', tier: 3, gender: 'M' },
  { id: '34', name: '김덕수', tier: 2, gender: 'M' },
  { id: '35', name: '김도우', tier: 2, gender: 'M' },
  { id: '36', name: '김동수', tier: 99, gender: 'M' },
  { id: '37', name: '김영무', tier: 99, gender: 'M' },
  { id: '38', name: '김영우', tier: 99, gender: 'M' },
  { id: '39', name: '하진', tier: 99, gender: 'M' },
  { id: '40', name: '한기언', tier: 2, gender: 'M' },
  { id: '41', name: '황재만', tier: 99, gender: 'M' },
];
